### ISSUE TITLE
Test failures on build

### ISSUE THREAD

**Issue by dmyersturnbull** [mesos/chronos#580] opened 2015-10-25 21:37 UTC
On the current build (#c91d2fb3), I get test failures (below). I get different test failures with release 2.4.0.

I can reproduce this on my Mac OS 10.10.5 system using:
```
git clone https://github.com/mesos/chronos.git
cd chronos
mvn install
```
I also tried the Dockerfile with Virtualbox and Docker 1.8.2.

Here are the test failures:
```
Failed tests: 
   'DependencyBasedJob(Set(B, C, D, E),A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test dependency-based job,TODAY,YESTERDAY,true,0.1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RO)), Volume(None,container/dir,None)),ListBuffer(),BRIDGE,false),ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),false,ListBuffer(-testOne),true,false,ListBuffer(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3])))'
 is not equal to 
'DependencyBasedJob(Set(B, C, D, E),A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test dependency-based job,TODAY,YESTERDAY,true,0.0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RO)), Volume(None,container/dir,None)),ListBuffer(),BRIDGE,false),List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),false,List(-testOne),true,false,List(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3])))' expected:<...AY,YESTERDAY,true,0.[0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RO)), Volume(None,container/dir,None)),ListBuffer(),BRIDGE,false),List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),false,List(-testOne),true,false,List](EqualsConstraint(ra...> but was:<...AY,YESTERDAY,true,0.[1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RO)), Volume(None,container/dir,None)),ListBuffer(),BRIDGE,false),ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),false,ListBuffer(-testOne),true,false,ListBuffer](EqualsConstraint(ra...>
   'ScheduleBasedJob(FOO/BAR/BAM,A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test schedule-based job,TODAY,YESTERDAY,true,0.1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,ListBuffer(-testOne),true,false,ListBuffer(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3])))'
 is not equal to 
'ScheduleBasedJob(FOO/BAR/BAM,A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test schedule-based job,TODAY,YESTERDAY,true,0.0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,List(-testOne),true,false,List(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3])))' expected:<...AY,YESTERDAY,true,0.[0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,List(-testOne),true,false,List](EqualsConstraint(ra...> but was:<...AY,YESTERDAY,true,0.[1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,ListBuffer(-testOne),true,false,ListBuffer](EqualsConstraint(ra...>

Tests run: 76, Failures: 2, Errors: 0, Skipped: 0

```

**Comment by Rob-Johnson** [comment] 2015-11-18 05:38
I have the same issue:

I built the a Docker image using the provided dockerfile:

```
root@62ee4b7eb627:/chronos# java -version
java version "1.7.0_85"
OpenJDK Runtime Environment (IcedTea 2.6.1) (7u85-2.6.1-5ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
```

```
root@62ee4b7eb627:/chronos# mvn -X clean package
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_85, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.1.12-boot2docker", arch: "amd64", family: "unix"
...

Results :

Failed tests:
   'ScheduleBasedJob(FOO/BAR/BAM,A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test schedule-based job,TODAY,YESTERDAY,true,0.1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,ListBuffer(-testOne),true,false,ListBuffer(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3]), UnlikeConstraint(host,foo)))'
 is not equal to
'ScheduleBasedJob(FOO/BAR/BAM,A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test schedule-based job,TODAY,YESTERDAY,true,0.0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,List(-testOne),true,false,List(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3]), UnlikeConstraint(host,foo)))' expected:<...AY,YESTERDAY,true,0.[0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,List(-testOne),true,false,List](EqualsConstraint(ra...> but was:<...AY,YESTERDAY,true,0.[1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,ListBuffer(-testOne),true,false,ListBuffer](EqualsConstraint(ra...>
   'DependencyBasedJob(Set(B, C, D, E),A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test dependency-based job,TODAY,YESTERDAY,true,0.1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RO)), Volume(None,container/dir,None)),ListBuffer(),BRIDGE,false),ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),false,ListBuffer(-testOne),true,false,ListBuffer(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3]), UnlikeConstraint(host,foo)))'
 is not equal to
'DependencyBasedJob(Set(B, C, D, E),A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test dependency-based job,TODAY,YESTERDAY,true,0.0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RO)), Volume(None,container/dir,None)),ListBuffer(),BRIDGE,false),List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),false,List(-testOne),true,false,List(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3]), UnlikeConstraint(host,foo)))' expected:<...AY,YESTERDAY,true,0.[0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RO)), Volume(None,container/dir,None)),ListBuffer(),BRIDGE,false),List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),false,List(-testOne),true,false,List](EqualsConstraint(ra...> but was:<...AY,YESTERDAY,true,0.[1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RO)), Volume(None,container/dir,None)),ListBuffer(),BRIDGE,false),ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),false,ListBuffer(-testOne),true,false,ListBuffer](EqualsConstraint(ra...>

Tests run: 81, Failures: 2, Errors: 0, Skipped: 0
```

To be clear, the ``run`` count is because of a PR I'm working on. I'm at the HEAD of master.

**Comment by Rob-Johnson** [comment] 2015-11-18 05:48
ah, seems this is a dupe of #558

**Closed** 2015-12-01 13:34 UTC
Labels: duplicate
